version: 2
jobs:
  build:
    docker:
      - image: cimg/node:14.16.0
    steps:
      - checkout
      - run: sudo apt-get update && sudo apt-get install -y python-dev
      - run: sudo curl -O https://bootstrap.pypa.io/pip/2.7/get-pip.py
      - run: sudo python get-pip.py
      - run: sudo pip install awscli --upgrade
      - run: aws --version
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 446481105531.dkr.ecr.us-east-2.amazonaws.com
            docker build -t staging-resource-api:latest .
            docker tag staging-resource-api:latest 446481105531.dkr.ecr.us-east-2.amazonaws.com/staging-resource-api:latest
            docker push 446481105531.dkr.ecr.us-east-2.amazonaws.com/staging-resource-api:latest
workflows:
  version: 2
  build-master:
    jobs:
      - build
